name: Submit New Item for Sale
description: Submit a new item listing to be added to the repository
title: "[NEW ITEM]: "
labels: ["new-item", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an item for sale! Please fill out the information below in both English and Polish.

        Dziękujemy za zgłoszenie przedmiotu na sprzedaż! Proszę wypełnić poniższe informacje w języku angielskim i polskim.

  - type: input
    id: item-id
    attributes:
      label: Item ID
      description: A unique identifier for this item (e.g., item-001, laptop-2025-001)
      placeholder: item-001
    validations:
      required: true

  - type: input
    id: title-en
    attributes:
      label: Item Title (English)
      description: A short, descriptive title for your item in English
      placeholder: Vintage Desk Lamp
    validations:
      required: true

  - type: input
    id: title-pl
    attributes:
      label: Item Title (Polish / Polski)
      description: A short, descriptive title for your item in Polish
      placeholder: Zabytkowa Lampa Biurkowa
    validations:
      required: true

  - type: textarea
    id: description-en
    attributes:
      label: Description (English)
      description: Detailed description of the item in English including condition, features, etc.
      placeholder: Beautiful brass desk lamp from the 1960s. Fully functional with new wiring...
    validations:
      required: true

  - type: textarea
    id: description-pl
    attributes:
      label: Description (Polish / Polski)
      description: Detailed description of the item in Polish including condition, features, etc.
      placeholder: Piękna mosiężna lampa biurkowa z lat 60-tych. W pełni sprawna z nowym okablowaniem...
    validations:
      required: true

  - type: input
    id: price
    attributes:
      label: Price
      description: Price for the item (numbers only)
      placeholder: "75.00"
    validations:
      required: true

  - type: dropdown
    id: currency
    attributes:
      label: Currency
      description: What currency is the price in?
      options:
        - PLN
        - EUR
        - USD
        - GBP
        - CAD
        - AUD
        - Other
      default: 0
    validations:
      required: true

  - type: dropdown
    id: condition
    attributes:
      label: Condition
      description: What condition is the item in?
      options:
        - new
        - like-new
        - good
        - fair
        - poor
      default: 2
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      description: What category does this item belong to?
      placeholder: furniture, electronics, clothing, etc.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the item available? (City or shipping details)
      placeholder: Warszawa / Odbiór osobisty / Wysyłka w Polsce
    validations:
      required: true

  - type: textarea
    id: images
    attributes:
      label: Image URLs
      description: |
        Upload images by dragging & dropping them here, OR paste image URLs (one per line).
        Images will be automatically downloaded and added to the repository.

        Prześlij zdjęcia przeciągając i upuszczając je tutaj, LUB wklej URL-e zdjęć (po jednym w linii).
        Zdjęcia zostaną automatycznie pobrane i dodane do repozytorium.
      placeholder: |
        https://example.com/image1.jpg
        https://example.com/image2.jpg

        Or drag and drop images here / Lub przeciągnij i upuść zdjęcia tutaj

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags for easier searching
      placeholder: vintage, lighting, brass, office

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have provided accurate information about this item
          required: true
        - label: I have the right to sell this item
          required: true
        - label: The price listed is final and includes any applicable fees
          required: true
